apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    {{- range .Values.service.ports }}
    {{- $containerPort := .containerPort | default .port }}
    {{- $protocol := .protocol | default "TCP" }}
    - name: {{ $protocol | lower }}-{{ .port }}
      protocol: {{ $protocol | quote }}
      targetPort: {{ $containerPort }}
      port: {{ .port }}
  {{- end }}
