name: Build Docker image and deploy Helm chart

on:
  push:
    branches: ['deploy']

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ileahu-ellation/crunchygram

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.5.0
        with:
          flavor: latest=true
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    env:
      KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: 'Remove'
        uses: 'deliverybot/helm@master'
        with:
          chart: './chart'
          release: 'crgram'
          namespace: 'default'
          helm: 'helm3'
          task: 'remove'

      - name: 'Deploy'
        uses: 'deliverybot/helm@master'
        with:
          chart: './chart'
          release: 'crgram'
          namespace: 'default'
          helm: 'helm3'
